/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
    public static void main(String[] args){
        roll(3);
        int [] x = {1,32,32,20,3,4,5};
        System.out.println(containsDuplicates(x));
        System.out.println(calculateAverage(x));
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println(averageOfLowestArray(weeklyMonthTemperatures));
    }

    public static int[] roll(int n){
        int min = 1;
        int max = 6;
        //generate random values from 0-24
        int [] result = new int[n];
        for(int i = 0 ; i<n ; i++){
            int dice_roll = (int)Math.floor(Math.random()*(max-min+1)+min);
            result[i] = dice_roll ;
        }
        System.out.println(Arrays.toString(result));
        return result;
    }

    static boolean containsDuplicates(int [] arr){
        boolean result = false;
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1 ; j < arr.length; j++) {
                if (arr[i]==(arr[j]))
                    result= true;

            }
        }
        return result;
    }

    static double calculateAverage(int [] arr){
        double sum =0;
        for (int i=0 ;i<arr.length ; i++){
            sum+=arr[i];
        }
        double average = sum/arr.length;
        return average;

    }

    static double averageOfLowestArray(int [][] arr){
        double [] averagesArray = new double[arr.length];
        for (int i=0; i<arr.length ; i++){
            averagesArray[i] = calculateAverage(arr[i]);
        }
        double min = averagesArray[0];
        for (int i=1 ; i<averagesArray.length ; i++){
            if(averagesArray[i]<= min)
                min = averagesArray[i];
        }
        return min;
    }
}
