/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void creatingAnInstance() {
        Restaurant newRestaurant = new Restaurant("shawermaji",4,"$$");
        assertEquals("Restaurant name: shawermaji, starRating:4.0, priceCategory:$$, Reviews: []",newRestaurant.toString());
    }
    @Test void testReview(){
        Review newReview = new Review("this restaurant has good burgers","ahmed",3.5);
        assertEquals("rating: 3.5, 'this restaurant has good burgers', reviewed by 'ahmed'",newReview.toString());
    }
    @Test void testAddReview(){
        Restaurant newRestaurant = new Restaurant("meat me",5,"$$$");
        Review newReview = new Review("this restaurant is the best in smoked meat","ahmed",5);
        newRestaurant.addReview(newReview);
        assertEquals(1,newRestaurant.getReviews().size());
        assertFalse(newRestaurant.getReviews().isEmpty());
    }
    @Test void testRating(){
        Restaurant newRestaurant = new Restaurant("buffalo",4,"$$$");
        Review newReview = new Review("this restaurant has the best wing in town","rania",4.5);
        newRestaurant.addReview(newReview);
        assertEquals(4.25,newRestaurant.getStarRating());
    }
}
