/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App test = new App();
    @Test public void testFileThatContainsManyErrors(){
    String path = "/Users/macbookpro/projects/401/java-fundamentals/linter/app/src/main/resources/gates.js";
    assertEquals("this file has 46 error/s",test.hasErrors(path));
    }
    @Test public void testFileThatContainsOneError(){
        String path ="/Users/macbookpro/projects/401/java-fundamentals/linter/app/src/main/resources/gatesOneError.js";
        assertEquals("this file has 1 error/s",test.hasErrors(path));
    }
    @Test public void testFileThatContainsFewError(){
        String path ="/Users/macbookpro/projects/401/java-fundamentals/linter/app/src/main/resources/gatesFewErrors.js";
        assertEquals("this file has 9 error/s",test.hasErrors(path));
    }
    @Test public void testFileThatContainsNoError(){
        String path ="/Users/macbookpro/projects/401/java-fundamentals/linter/app/src/main/resources/gatesNoErrors.js";
        assertEquals("this file has no errors",test.hasErrors(path));
    }
}
